import { lazy } from 'react';

const pageLoaders = import.meta.glob('../pages/{Admin,Clerk,Student,Teacher,common}/**/*.jsx');

const resolvePageLoader = (path) => {
  const loader = pageLoaders[`${path}.jsx`] || pageLoaders[path];
  if (!loader) {
    throw new Error(`Missing page module for ${path}`);
  }

  return loader;
};

const lazyPage = (path) => lazy(resolvePageLoader(path));

export const portalRoutes = {
  admin: {
    defaultPage: 'Dashboard',
    pages: {
      Dashboard: lazyPage('../pages/Admin/Dashboard'),
      'Academic Calender': lazyPage('../pages/Admin/AcademicCalender'),
      Application: lazyPage('../pages/Admin/Application'),
      Assignment: lazyPage('../pages/Admin/Assignment'),
      Attendance: lazyPage('../pages/Admin/Attendance'),
      'Admin Management': lazyPage('../pages/Admin/AdminManagement'),
      'Class Management': lazyPage('../pages/Admin/ClassManagement'),
      'Clerk Management': lazyPage('../pages/Admin/ClerkManagement'),
      'Clerk Profile': lazyPage('../pages/Admin/ClerkProfile'),
      'Documents Management': lazyPage('../pages/Admin/DocumentsManagement'),
      Events: lazyPage('../pages/Admin/Events'),
      Examinations: lazyPage('../pages/Admin/Examinations'),
      'Exam Creation': lazyPage('../pages/Admin/Examinations'),
      'Paper Creation': lazyPage('../pages/Admin/Examinations'),
      'Paper Analysis': lazyPage('../pages/Admin/Examinations'),
      'Paper Selected': lazyPage('../pages/Admin/Examinations'),
      'Report Card Management': lazyPage('../pages/Admin/Examinations'),
      'Marks Management': lazyPage('../pages/Admin/Examinations'),
      'Feature Page': lazyPage('../pages/Admin/FeaturePage'),
      Finance: lazyPage('../pages/Admin/Finance'),
      Payroll: lazyPage('../pages/Admin/Payroll'),
      'Id Card': lazyPage('../pages/Admin/IdCard'),
      'Leave Requests': lazyPage('../pages/Admin/LeaveRequests'),
      Meetings: lazyPage('../pages/Admin/Meetings'),
      Notices: lazyPage('../pages/Admin/Notices'),
      Profile: lazyPage('../pages/Admin/Profile'),
      'Student Ledger': lazyPage('../pages/Admin/StudentLedger'),
      'Student Profile': lazyPage('../pages/Admin/StudentProfile'),
      'Subject Management': lazyPage('../pages/Admin/SubjectManagement'),
      'Teacher Management': lazyPage('../pages/Admin/TeacherManagement'),
      'Teacher Assignment': lazyPage('../pages/Admin/TeacherAssignment'),
      'Teacher Profile': lazyPage('../pages/Admin/TeacherProfile'),
      'Class Finance List': lazyPage('../pages/Admin/ClassFinanceList'),
      Timetable: lazyPage('../pages/Admin/Timetable'),
      Settings: lazyPage('../pages/Admin/Settings'),
      'Student Assigning': lazyPage('../pages/Admin/StudentAssigning'),
      'Student Management': lazyPage('../pages/Admin/StudentManagement'),
      'Sibling Assigning': lazyPage('../pages/Admin/SiblingAssigning'),
      'Class Preferences': lazyPage('../pages/Admin/ClassPreferences'),
      'Fees Receipt': lazyPage('../pages/Admin/FeesReceipt'),
      'Users Management': lazyPage('../pages/Admin/UsersManagement'),
      Vault: lazyPage('../pages/Admin/Vault'),
    },
  },
  clerk: {
    defaultPage: 'Dashboard',
    pages: {
      Dashboard: lazyPage('../pages/Clerk/Dashboard'),
      'Academic Calender': lazyPage('../pages/Clerk/AcademicCalender'),
      Application: lazyPage('../pages/Clerk/Application'),
      Assignment: lazyPage('../pages/Clerk/Assignment'),
      Attendance: lazyPage('../pages/Clerk/Attendance'),
      'Class Management': lazyPage('../pages/Clerk/ClassManagement'),
      'Class Preferences': lazyPage('../pages/Clerk/ClassPreferences'),
      'Documents Management': lazyPage('../pages/Clerk/DocumentsManagement'),
      Events: lazyPage('../pages/Clerk/Events'),
      Examinations: lazyPage('../pages/Clerk/Examinations'),
      'Exam Creation': lazyPage('../pages/Clerk/Examinations'),
      'Paper Creation': lazyPage('../pages/Clerk/Examinations'),
      'Paper Analysis': lazyPage('../pages/Clerk/Examinations'),
      'Paper Selected': lazyPage('../pages/Clerk/Examinations'),
      'Marks Management': lazyPage('../pages/Clerk/Examinations'),
      'Id Card': lazyPage('../pages/Clerk/IdCard'),
      'Leave Requests': lazyPage('../pages/Clerk/LeaveRequests'),
      Meetings: lazyPage('../pages/Clerk/Meetings'),
      Notices: lazyPage('../pages/Clerk/Notices'),
      Profile: lazyPage('../pages/Clerk/Profile'),
      'My Salary': lazyPage('../pages/common/MySalary'),
      Settings: lazyPage('../pages/Clerk/Settings'),
      'Sibling Assigning': lazyPage('../pages/Clerk/SiblingAssigning'),
      'Student Assigning': lazyPage('../pages/Clerk/StudentAssigning'),
      'Student Management': lazyPage('../pages/Clerk/StudentManagement'),
      'Student Profile': lazyPage('../pages/Clerk/StudentProfile'),
      'Subject Management': lazyPage('../pages/Clerk/SubjectManagement'),
      'Teacher Assignment': lazyPage('../pages/Clerk/TeacherAssignment'),
      'Teacher Management': lazyPage('../pages/Clerk/TeacherManagement'),
      'Teacher Profile': lazyPage('../pages/Clerk/TeacherProfile'),
      Timetable: lazyPage('../pages/Clerk/Timetable'),
      Vault: lazyPage('../pages/Clerk/Vault'),
    },
  },
  student: {
    defaultPage: 'Dashboard',
    pages: {
      Dashboard: lazyPage('../pages/Student/Dashboard'),
      'Academic Calender': lazyPage('../pages/Student/AcademicCalender'),
      'My Class': lazyPage('../pages/Student/MyClass'),
      Timetable: lazyPage('../pages/Student/Timetable'),
      Application: lazyPage('../pages/Student/Application'),
      Assignment: lazyPage('../pages/Student/Assignment'),
      Attendance: lazyPage('../pages/Student/Attendance'),
      Events: lazyPage('../pages/Student/Events'),
      Examinations: lazyPage('../pages/Student/Examinations'),
      Fees: lazyPage('../pages/Student/Fees'),
      'Id Card': lazyPage('../pages/Student/IdCard'),
      'Leave Requests': lazyPage('../pages/Student/LeaveRequests'),
      Meetings: lazyPage('../pages/Student/Meetings'),
      Notices: lazyPage('../pages/Student/Notices'),
      Profile: lazyPage('../pages/Student/Profile'),
      Settings: lazyPage('../pages/Student/Settings'),
      Vault: lazyPage('../pages/Student/Vault'),
    },
  },
  teacher: {
    defaultPage: 'Dashboard',
    pages: {
      Dashboard: lazyPage('../pages/Teacher/Dashboard'),
      'Academic Calender': lazyPage('../pages/Teacher/AcademicCalender'),
      'My Class': lazyPage('../pages/Teacher/MyClass'),
      Timetable: lazyPage('../pages/Teacher/Timetable'),
      Application: lazyPage('../pages/Teacher/Application'),
      Assignment: lazyPage('../pages/Teacher/Assignment'),
      Attendance: lazyPage('../pages/Teacher/Attendance'),
      Events: lazyPage('../pages/Teacher/Events'),
      Examinations: lazyPage('../pages/Teacher/Examinations'),
      'Paper Analysis': lazyPage('../pages/Teacher/Examinations'),
      'Marks Management': lazyPage('../pages/Teacher/Examinations'),
      'Id Card': lazyPage('../pages/Teacher/IdCard'),
      'Leave Requests': lazyPage('../pages/Teacher/LeaveRequests'),
      Meetings: lazyPage('../pages/Teacher/Meetings'),
      Notices: lazyPage('../pages/Teacher/Notices'),
      Profile: lazyPage('../pages/Teacher/Profile'),
      'My Salary': lazyPage('../pages/common/MySalary'),
      Settings: lazyPage('../pages/Teacher/Settings'),
      Vault: lazyPage('../pages/Teacher/Vault'),
    },
  },
};
