export const CLERK_CLASSES = [
  'Nursery',
  'LKG',
  'UKG',
  'Class 1',
  'Class 2',
  'Class 3',
  'Class 4',
  'Class 5',
  'Class 6',
  'Class 7',
  'Class 8',
  'Class 9',
  'Class 10',
  'Class 11',
  'Class 12',
];

export const getClerkProfile = (session = {}) => ({
  id: session?.username || 'CLK-201',
  name: session?.displayName || 'Amit Sharma',
  username: session?.username || 'CLK-201',
  email: 'clerk.office@mgps.edu.in',
  mobile: '9829002211',
  department: 'Main Office Desk',
  role: 'Clerk / Records Operator',
  joiningDate: '15-Apr-2024',
  shift: '08:00 AM - 03:00 PM',
  deskWindow: 'Accounts and Records Counter 2',
});

export const getInitials = (name = '') =>
  name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part.charAt(0).toUpperCase())
    .join('') || 'MG';

export const formatShortDate = (value) => {
  if (!value) return 'Not set';

  return new Date(value).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
};

export const CLERK_STUDENTS = [
  {
    id: 'STD-301',
    admissionNumber: 'MGPS-2026-301',
    name: 'Parv Choudhary',
    className: 'Class 9',
    section: 'A',
    rollNo: 11,
    guardian: 'Rajesh Choudhary',
    phone: '9829012345',
    bloodGroup: 'B+',
    house: 'Tagore House',
    transport: 'Route 2',
    status: 'Active',
  },
  {
    id: 'STD-302',
    admissionNumber: 'MGPS-2026-302',
    name: 'Ananya Sharma',
    className: 'Class 9',
    section: 'A',
    rollNo: 14,
    guardian: 'Manoj Sharma',
    phone: '9414012345',
    bloodGroup: 'O+',
    house: 'Tagore House',
    transport: 'Route 3',
    status: 'Active',
  },
  {
    id: 'STD-303',
    admissionNumber: 'MGPS-2026-303',
    name: 'Kabir Malhotra',
    className: 'Class 9',
    section: 'B',
    rollNo: 18,
    guardian: 'Sanjay Malhotra',
    phone: '9351112233',
    bloodGroup: 'A+',
    house: 'Raman House',
    transport: 'Self',
    status: 'Active',
  },
  {
    id: 'STD-401',
    admissionNumber: 'MGPS-2026-401',
    name: 'Isha Patel',
    className: 'Class 10',
    section: 'A',
    rollNo: 7,
    guardian: 'Nilesh Patel',
    phone: '9829100176',
    bloodGroup: 'AB+',
    house: 'Bose House',
    transport: 'Route 1',
    status: 'Active',
  },
  {
    id: 'STD-402',
    admissionNumber: 'MGPS-2026-402',
    name: 'Rahul Kumar',
    className: 'Class 10',
    section: 'B',
    rollNo: 24,
    guardian: 'Suresh Kumar',
    phone: '9414234567',
    bloodGroup: 'O-',
    house: 'Raman House',
    transport: 'Route 5',
    status: 'Verification',
  },
  {
    id: 'STD-501',
    admissionNumber: 'MGPS-2026-501',
    name: 'Meera Singh',
    className: 'Class 6',
    section: 'B',
    rollNo: 6,
    guardian: 'Pratap Singh',
    phone: '9828770032',
    bloodGroup: 'A-',
    house: 'Tagore House',
    transport: 'Route 4',
    status: 'Active',
  },
  {
    id: 'STD-502',
    admissionNumber: 'MGPS-2026-502',
    name: 'Aarav Sharma',
    className: 'Class 6',
    section: 'A',
    rollNo: 13,
    guardian: 'Rajesh Sharma',
    phone: '9876543210',
    bloodGroup: 'B+',
    house: 'Tagore House',
    transport: 'Route 4',
    status: 'Active',
  },
  {
    id: 'STD-601',
    admissionNumber: 'MGPS-2026-601',
    name: 'Naina Verma',
    className: 'Class 3',
    section: 'A',
    rollNo: 9,
    guardian: 'Harish Verma',
    phone: '9350021456',
    bloodGroup: 'O+',
    house: 'Bose House',
    transport: 'Route 2',
    status: 'Active',
  },
];

export const CLERK_STAFF = [
  {
    id: 'TCH-501',
    name: 'Dr. Ramesh Verma',
    role: 'Teacher',
    department: 'Physics',
    phone: '9876501234',
    email: 'ramesh.verma@mgps.edu.in',
  },
  {
    id: 'TCH-502',
    name: 'Mrs. Sunita Sharma',
    role: 'Teacher',
    department: 'Primary Wing',
    phone: '9876505678',
    email: 'sunita.sharma@mgps.edu.in',
  },
  {
    id: 'CLK-201',
    name: 'Amit Sharma',
    role: 'Clerk',
    department: 'Records',
    phone: '9829002211',
    email: 'clerk.office@mgps.edu.in',
  },
];

export const CLERK_ATTENDANCE_REGISTERS = [
  {
    id: 'ATT-9A',
    className: 'Class 9',
    section: 'A',
    teacher: 'Dr. Ramesh Verma',
    present: 38,
    absent: 2,
    late: 1,
    total: 41,
    status: 'Submitted',
  },
  {
    id: 'ATT-9B',
    className: 'Class 9',
    section: 'B',
    teacher: 'Teacher Faculty',
    present: 35,
    absent: 4,
    late: 0,
    total: 39,
    status: 'Review',
  },
  {
    id: 'ATT-10A',
    className: 'Class 10',
    section: 'A',
    teacher: 'Mrs. Kavita Rao',
    present: 42,
    absent: 1,
    late: 2,
    total: 45,
    status: 'Submitted',
  },
  {
    id: 'ATT-6B',
    className: 'Class 6',
    section: 'B',
    teacher: 'Mrs. Sunita Sharma',
    present: 31,
    absent: 3,
    late: 1,
    total: 35,
    status: 'Pending',
  },
];

export const CLERK_TASKS = [
  {
    id: 'TASK-01',
    label: 'Verify Class 6B attendance correction',
    owner: 'Attendance Desk',
    priority: 'High',
    page: 'Attendance',
  },
  {
    id: 'TASK-02',
    label: 'Publish transport fee reminder notice',
    owner: 'Accounts Desk',
    priority: 'Normal',
    page: 'Notices',
  },
  {
    id: 'TASK-03',
    label: 'Prepare ID card print batch for Class 9A',
    owner: 'Records Desk',
    priority: 'Normal',
    page: 'Id Card',
  },
  {
    id: 'TASK-04',
    label: 'Review new admission document packets',
    owner: 'Document Desk',
    priority: 'High',
    page: 'Documents Management',
  },
];

export const CLERK_MESSAGES = [
  {
    id: 'MSG-01',
    channelId: 'broadcast',
    sender: 'Admin Office',
    role: 'Admin',
    body: 'Please keep the Q1 fee clearance desk open until 02:30 PM today.',
    time: 'Today, 09:15 AM',
  },
  {
    id: 'MSG-02',
    channelId: 'teachers',
    sender: 'Dr. Ramesh Verma',
    role: 'Teacher',
    body: 'Class 9A attendance has one student marked late due to lab duty.',
    time: 'Today, 10:05 AM',
  },
  {
    id: 'MSG-03',
    channelId: 'class-9',
    sender: 'Clerk Desk',
    role: 'Clerk',
    body: 'Class 9 ID cards will be issued after lunch from Counter 2.',
    time: 'Yesterday, 01:25 PM',
  },
];

export const CLERK_MEETINGS = [
  {
    id: 'MTG-101',
    title: 'Fee Defaulter Follow-up',
    audience: 'Accounts Team',
    date: '2026-05-24',
    time: '10:30 AM',
    mode: 'Office Room',
    owner: 'Principal Office',
    status: 'Scheduled',
  },
  {
    id: 'MTG-102',
    title: 'Class 9 ID Card Distribution',
    audience: 'Class Teachers',
    date: '2026-05-25',
    time: '12:00 PM',
    mode: 'Records Counter',
    owner: 'Clerk Desk',
    status: 'Scheduled',
  },
  {
    id: 'MTG-103',
    title: 'Document Verification Review',
    audience: 'Admission Team',
    date: '2026-05-26',
    time: '09:45 AM',
    mode: 'Admin Office',
    owner: 'Admin Office',
    status: 'Pending Notes',
  },
];

export const CLERK_NOTICES = [
  {
    id: 'NTC-901',
    title: 'Quarter 1 Fee Payment Reminder',
    category: 'Accounts',
    date: '2026-05-22',
    body: 'Parents are requested to clear tuition and transport fee dues before the first week of June.',
    targets: ['All Classes'],
    status: 'Published',
  },
  {
    id: 'NTC-902',
    title: 'Class 9 ID Card Collection',
    category: 'Records',
    date: '2026-05-21',
    body: 'Class 9 students should collect ID cards from the main office counter after lunch break.',
    targets: ['Class 9'],
    status: 'Published',
  },
];

export const CLERK_DOCUMENT_QUEUE = [
  {
    id: 'DOC-101',
    ownerName: 'Rahul Kumar',
    ownerType: 'Student',
    className: 'Class 10-B',
    packet: 'New Admission Packet',
    submitted: '2026-05-20',
    status: 'Review',
    documents: [
      { name: 'Student Photo', status: 'Verified' },
      { name: 'Aadhaar Card', status: 'Review' },
      { name: 'Birth Certificate', status: 'Pending' },
    ],
  },
  {
    id: 'DOC-102',
    ownerName: 'Mrs. Sunita Sharma',
    ownerType: 'Teacher',
    className: 'Primary Wing',
    packet: 'Faculty Joining Packet',
    submitted: '2026-05-18',
    status: 'Verified',
    documents: [
      { name: 'B.Ed Degree', status: 'Verified' },
      { name: 'Experience Certificate', status: 'Verified' },
      { name: 'Police Verification', status: 'Verified' },
    ],
  },
  {
    id: 'DOC-103',
    ownerName: 'Meera Singh',
    ownerType: 'Student',
    className: 'Class 6-B',
    packet: 'Transport Update Packet',
    submitted: '2026-05-22',
    status: 'Hold',
    documents: [
      { name: 'Guardian Consent', status: 'Review' },
      { name: 'Address Proof', status: 'Hold' },
      { name: 'Route Form', status: 'Verified' },
    ],
  },
];
